- name: Download repo file
  ansible.builtin.get_url:
    url: https://download.docker.com/linux/rhel/docker-ce.repo
    dest: /etc/yum.repos.d/docker-ce.repo

- name: Install Docker
  ansible.builtin.dnf:
    name: docker-ce
    state: installed

- name: Start Docker
  ansible.builtin.systemd_service:
    name: docker
    state: started
    enabled: yes

- name: Create Runner Containers
  loop:
    - runner-1
    - runner-2
    - runner-3
  community.docker.docker_container:
    name: "{{ item }}"
    image: udaych123/github-runner
    pull: always
    state: started
    restart: true
    restart_policy: always
    env:
      ORG: "https://github.com/golive123"
      TOKEN: "BTIL2UNECSVLM7QWA3KLG6DIIMM2C"
      NAME: "{{ item }}"