- name: Download repo file
  ansible.builtin.get_url:
    url: https://download.docker.com/linux/rhel/docker-ce.repo
    dest: /etc/yum.repos.d/docker-ce.repo

- name: Install Docker
  ansible.builtin.dnf:
    name: docker-ce
    state: installed

- name: Start Docker
  ansible.builtin.systemd_service:
    name: docker
    state: started
    enabled: yes

- name: Create Runner Containers
  loop:
    - runner-1
    - runner-2
    - runner-3
  community.docker.docker_container:
    name: "{{ item }}"
    image: udaych123/github-runner
    pull: true
    state: started
    restart: true
    restart_policy: always
    env:
     ORG: "{{ lookup('community.hashi_vault.hashi_vault', 'secret=/data/github-runner:ORG token={{ token }} url=http://vault.yourtherapist.in:8200/') }}"
     TOKEN: "{{ lookup('community.hashi_vault.hashi_vault', 'secret=/data/github-runner:TOKEN token={{ token }} url=http://vault.yourtherapist.in:8200/') }}"
     NAME: "{{ item }}"
     # ORG: "https://github.com/golive123"
      #TOKEN: "BTIL2UICYBVEH7JMJ5IVFWLIIMUUK"
      #NAME: "{{ item }}"